import Head from "next/head";
import styles from "../styles/Home.module.css";

// import { Button } from "@chakra-ui/react";
// import sendNotification from "../utils/sendNotification";

export default function Home() {
  // const sendTargetNotifHandler = async () => {
  //   console.log("TARGET");
  //   await sendNotification({
  //     type: 3,
  //     title: "test target notif",
  //     body: "body of test target notif",
  //     recipientAddresses: ["0x0E0c0541C6F78514C91040d9959D38578137aC0e"],
  //   });
  // };

  // const sendBroadcastNotifHandler = async () => {
  //   console.log("BROADCAST");
  //   await sendNotification({
  //     type: 1,
  //     title: "test broadcast notif",
  //     body: "body of test broadcast notif",
  //   });
  // };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <Button onClick={sendTargetNotifHandler}>
          Send Notification - target mode
        </Button>
        <Button onClick={sendBroadcastNotifHandler}>
          Send Notification - broadcast mode
        </Button> */}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
